services:

  azuracast-mqtt:
    image: n8acl/azuracast_to_mqtt:latest
    # build: .
    container_name: azuracast-mqtt
    volumes:
      - /<PATH-TO>/azuracast-to-mqtt/config.json:/app/config.json
    restart: unless-stopped